### ISSUE TITLE
How does one "optionally" use a small amount of RAM?  

### ISSUE THREAD

**Issue by alanhoyle** [arshajii/lava#2]
ON the main LAVA page, it says, "optionally using as little as 5.2 GB of RAM."  How do I make it use less RAM?

**Comment by arshajii** [comment]
The two things you can do are:
- Filter the reference dictionary using `lava filt`. Just make sure to set `GEN_FLT_DATA` to `1` before generating the dictionaries.
- Use a compact pileup table by setting `PCOMPACT` to `1`.

The constants are all defined in `include/lava.h`. Let me know if you run into any issues. Also note that the RAM usage will be dependent on the size of your SNP list; that 5.2 GB number is based on the SNP list from the Affymetrix SNP array.
